#!/usr/bin/env bash
#salam

deqiqe=1
saat=0

while (( saat <= 12 )); do
    echo "Hour: $saat"

    while (( deqiqe <= 59 )); do
        echo "$deqiqe"
        ((deqiqe++))
    done

    deqiqe=1
    ((saat++))
done
